version: '3'
services:
  api:
    build: .
    image: carplate:latest
    container_name: api
    ports:
      - "8000:8000"
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - rabbit
      - db
  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  celery:
    build: .
    image: carplate:latest
    container_name: celery
    command: celery -A CarplateAPI worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbit
  flower:
    build: .
    image: carplate:latest
    container_name: celery-ui
    command: celery -A CarplateAPI flower
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbit
    ports:
      - "5555:5555"
volumes:
  postgres_data:
